// <auto-generated />
using System;
using IMDArchitecture.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IMDArchitecture.API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211229130323_InitialCreate15")]
    partial class InitialCreate15
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("IMDArchitecture.API.Domain.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Date")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxAge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinAge")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParticipantCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("IMDArchitecture.API.Domain.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Administrator")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Firstname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lastname")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IMDArchitecture.API.Domain.UserEvent", b =>
                {
                    b.Property<int>("UserEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enrolled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventRelationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EventsEventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegisterTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserRelationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsersUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserEventId");

                    b.HasIndex("EventsEventId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("UserEvents");
                });

            modelBuilder.Entity("IMDArchitecture.API.Domain.UserEvent", b =>
                {
                    b.HasOne("IMDArchitecture.API.Domain.Event", "Events")
                        .WithMany("UserEvents")
                        .HasForeignKey("EventsEventId");

                    b.HasOne("IMDArchitecture.API.Domain.User", "Users")
                        .WithMany("UserEvents")
                        .HasForeignKey("UsersUserId");

                    b.Navigation("Events");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("IMDArchitecture.API.Domain.Event", b =>
                {
                    b.Navigation("UserEvents");
                });

            modelBuilder.Entity("IMDArchitecture.API.Domain.User", b =>
                {
                    b.Navigation("UserEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
